=== themiwi/ParaView3-enhancements-old/Plugins/VisTrails/vistrails/db/versions/v0_6_0/schemas/xml/vistrail.xsd
############################################################################
##
## Copyright (C) 2006-2007 University of Utah. All rights reserved.
##
## This file is part of VisTrails.
##
## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE.GPL included in the packaging of
## this file.  Please review the following to ensure GNU General Public
## Licensing requirements will be met:
## http://www.opensource.org/licenses/gpl-license.php
##
## If you are unsure which license is appropriate for your use (for
## instance, you are interested in developing a commercial derivative
## of VisTrails), please contact us at vistrails@sci.utah.edu.
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
############################################################################

<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="vistrail">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="action" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tag" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="abstraction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="version" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="dbHost" type="xs:string"/>
      <xs:attribute name="dbPort" type="xs:int"/>
      <xs:attribute name="dbName" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="action">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice>
          <xs:element ref="add" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="delete" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="change" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="prevId" type="xs:int"/>
      <xs:attribute name="date" type="xs:dateTime"/>
      <xs:attribute name="user" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tag">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="abstraction">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="action" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tag" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="annotation">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="key" type="xs:string"/>
      <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="add">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="module" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="connection" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="port" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="portSpec" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="abstractionRef" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="other" minOccurs="0" maxOccurs="1"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="what" type="xs:string"/>
      <xs:attribute name="objectId" type="xs:int"/>
      <xs:attribute name="parentObjId" type="xs:int"/>
      <xs:attribute name="parentObjType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="delete">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="what" type="xs:string"/>
      <xs:attribute name="objectId" type="xs:int"/>
      <xs:attribute name="parentObjId" type="xs:int"/>
      <xs:attribute name="parentObjType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="change">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="module" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="connection" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="port" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="portSpec" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="abstractionRef" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="other" minOccurs="0" maxOccurs="1"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="what" type="xs:string"/>
      <xs:attribute name="oldObjId" type="xs:int"/>
      <xs:attribute name="newObjId" type="xs:int"/>
      <xs:attribute name="parentObjId" type="xs:int"/>
      <xs:attribute name="parentObjType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="module">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="portSpec" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="cache" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="package" type="xs:string"/>
      <xs:attribute name="version" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="location">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="x" type="xs:float"/>
      <xs:attribute name="y" type="xs:float"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="pos" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="connection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="port" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="port">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="moduleId" type="xs:int"/>
      <xs:attribute name="moduleName" type="xs:string"/>
      <xs:attribute name="sig" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="pos" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="val" type="xs:string"/>
      <xs:attribute name="alias" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="portSpec">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="spec" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="abstractionRef">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="abstractionId" type="xs:int"/>
      <xs:attribute name="version" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="other">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="value" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="key" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== themiwi/ParaView3-enhancements-old/Plugins/VisTrails/vistrails/tests/resources/test_abstraction.xml
<?xml version="1.0" ?>
<vistrail dbHost="" dbName="" dbPort="" id="" name="" version="0.7.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vistrails.org/vistrail.xsd">
  <action date="2007-08-27 17:13:44" id="1" prevId="0" prune="" session="" user="dakoop">
    <add id="0" objectId="0" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="0" name="Float" package="edu.utah.sci.vistrails.basic" version=""/>
    </add>
    <add id="1" objectId="0" parentObjId="0" parentObjType="module" what="location">
      <location id="0" x="62.0" y="180.0"/>
    </add>
  </action>
  <action date="2007-08-27 17:13:46" id="2" prevId="1" prune="" session="" user="dakoop">
    <add id="2" objectId="1" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="1" name="Float" package="edu.utah.sci.vistrails.basic" version=""/>
    </add>
    <add id="3" objectId="1" parentObjId="1" parentObjType="module" what="location">
      <location id="1" x="-109.0" y="146.0"/>
    </add>
  </action>
  <action date="2007-08-27 17:13:51" id="3" prevId="2" prune="" session="" user="dakoop">
    <add id="4" objectId="2" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="2" name="List" package="edu.utah.sci.vistrails.basic" version=""/>
    </add>
    <add id="5" objectId="2" parentObjId="2" parentObjType="module" what="location">
      <location id="2" x="18.0" y="85.0"/>
    </add>
  </action>
  <action date="2007-08-27 17:13:53" id="4" prevId="3" prune="" session="" user="dakoop">
    <add id="6" objectId="3" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="3" name="List" package="edu.utah.sci.vistrails.basic" version=""/>
    </add>
    <add id="7" objectId="3" parentObjId="3" parentObjType="module" what="location">
      <location id="3" x="17.0" y="-31.0"/>
    </add>
  </action>
  <action date="2007-08-27 17:13:57" id="5" prevId="4" prune="" session="" user="dakoop">
    <add id="8" objectId="0" parentObjId="" parentObjType="" what="connection">
      <connection id="0"/>
    </add>
    <add id="9" objectId="1" parentObjId="0" parentObjType="connection" what="port">
      <port id="1" moduleId="2" moduleName="List" name="head" spec="(edu.utah.sci.vistrails.basic:Module)" type="destination"/>
    </add>
    <add id="10" objectId="0" parentObjId="0" parentObjType="connection" what="port">
      <port id="0" moduleId="1" moduleName="Float" name="value" spec="(edu.utah.sci.vistrails.basic:Float)" type="source"/>
    </add>
  </action>
  <action date="2007-08-27 17:14:03" id="6" prevId="5" prune="" session="" user="dakoop">
    <delete id="11" objectId="1" parentObjId="0" parentObjType="connection" what="port"/>
    <delete id="12" objectId="0" parentObjId="0" parentObjType="connection" what="port"/>
    <delete id="13" objectId="0" parentObjId="" parentObjType="" what="connection"/>
  </action>
  <action date="2007-08-27 17:14:06" id="7" prevId="6" prune="" session="" user="dakoop">
    <add id="14" objectId="1" parentObjId="" parentObjType="" what="connection">
      <connection id="1"/>
    </add>
    <add id="15" objectId="3" parentObjId="1" parentObjType="connection" what="port">
      <port id="3" moduleId="3" moduleName="List" name="head" spec="(edu.utah.sci.vistrails.basic:Module)" type="destination"/>
    </add>
    <add id="16" objectId="2" parentObjId="1" parentObjType="connection" what="port">
      <port id="2" moduleId="1" moduleName="Float" name="value" spec="(edu.utah.sci.vistrails.basic:Float)" type="source"/>
    </add>
  </action>
  <action date="2007-08-27 17:14:09" id="8" prevId="7" prune="" session="" user="dakoop">
    <add id="17" objectId="2" parentObjId="" parentObjType="" what="connection">
      <connection id="2"/>
    </add>
    <add id="18" objectId="5" parentObjId="2" parentObjType="connection" what="port">
      <port id="5" moduleId="2" moduleName="List" name="head" spec="(edu.utah.sci.vistrails.basic:Module)" type="destination"/>
    </add>
    <add id="19" objectId="4" parentObjId="2" parentObjType="connection" what="port">
      <port id="4" moduleId="0" moduleName="Float" name="value" spec="(edu.utah.sci.vistrails.basic:Float)" type="source"/>
    </add>
  </action>
  <action date="2007-08-27 17:14:11" id="9" prevId="8" prune="" session="" user="dakoop">
    <add id="20" objectId="3" parentObjId="" parentObjType="" what="connection">
      <connection id="3"/>
    </add>
    <add id="21" objectId="7" parentObjId="3" parentObjType="connection" what="port">
      <port id="7" moduleId="3" moduleName="List" name="tail" spec="(edu.utah.sci.vistrails.basic:List)" type="destination"/>
    </add>
    <add id="22" objectId="6" parentObjId="3" parentObjType="connection" what="port">
      <port id="6" moduleId="2" moduleName="List" name="value" spec="(edu.utah.sci.vistrails.basic:List)" type="source"/>
    </add>
  </action>
</vistrail>
